# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8hWPKm3tH_rrYw82iZM3rpkC6WCXk8Y
"""

#task1

task1_input = open(file='input1_1.txt', mode='r')
task1_output = open(file='output1_1.txt', mode='w')

lst = task1_input.readline().strip().split(" ")

total_cost= 0

x = int(lst[0])
y = int(lst[1])

save_lis = []

for i in range(y):
    lst2 = task1_input.readline().strip().split()
    u = int(lst2[0])
    v = int(lst2[1])
    w = int(lst2[2])

    save_lis.append((u,v,w))



temp = [[] for i in range(x + 1)]

for u,v,w in save_lis:

    temp[u].append((v,w))
    temp[v].append((u,w))

store = set()
store.add(1)

while len(store) < x:
    min_cost = float('inf')

    min_city = None

    for i in store:

        for y, z in temp[i]:

            if y not in store and  z < min_cost :
                min_cost= z
                min_city= y

    store.add(min_city)

    total_cost += min_cost

task1_output.write(str(total_cost))

task1_input.close()
task1_output.close()