# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8hWPKm3tH_rrYw82iZM3rpkC6WCXk8Y
"""

#task2

task2_input = open(file='input2_3.txt', mode='r')
task2_output = open(file='output2_3.txt', mode='w')

num = int(task2_input.readline())

def number_of_ways (num):

    if num == 1 :
        return 1
    if num == 2 :
        return 2

    temp =  [0] * (num + 1)

    temp[1] = 1

    temp[2] = 2

    for i in range(3, num + 1) :

        temp [i] = temp[i - 1] + temp [i - 2]

    return temp[num]

ans = number_of_ways(num)

task2_output.write(str(ans))

task2_input.close()
task2_output.close()