# -*- coding: utf-8 -*-
"""task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDq-XTyJ-Chu-ZpCimAl4lCTG2_7IgVw
"""

# Task 1a : using readlines()
task1a_input = open(input1a.txt', mode='r')
task1a_output = open(output1a.txt', mode='w')
num_of_line = int(task1a_input.readline().strip())
for i in range(num_of_line):
    temp = int(task1a_input.readline().strip())
    if temp%2 == 0:
        s = f"{temp} is an Even number. \n"
        task1a_output.write(s)
    else:
        s = f"{temp} is a Odd number. \n"
        task1a_output.write(s)