# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDq-XTyJ-Chu-ZpCimAl4lCTG2_7IgVw
"""

#Task 4

task4_input = open(input4.txt', mode='r')
task4_output = open(output4.txt', mode='w')
name = []
desti = []
time = []
new_list = []
num = int(task4_input.readline())
for i in range(num):
    temp = task4_input.readline().split()
    name.append(temp[0])
    desti.append(temp[4])
    time.append(temp[6])
    new_list.append([name[i],desti[i],time[i]])

for i in range(num-1):
    for j in range(num-i-1):
        if new_list[j][0] > new_list[j+1][0]:
            new_list[j], new_list[j+1] = new_list[j+1],new_list[j]

        elif new_list[j][0] == new_list[j+1][0]:
            if new_list[j][2] < new_list[j+1][2]:
                new_list[j], new_list[j+1] = new_list[j+1],new_list[j]


        elif new_list[j] == new_list[j+1] and new_list[j] == new_list[j+1]:
            continue
for i in range(len(new_list)):
    task4_output.write(f"{str(new_list[i][0])} will departure for {str(new_list[i][1])} at {str(new_list[i][2])}\n")