# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDq-XTyJ-Chu-ZpCimAl4lCTG2_7IgVw
"""

#Task 2
task2_input = open(input2.txt', mode='r')
task2_output = open(output2.txt', mode='w')

num_of_line = int(task2_input.readline())
second = task2_input.readline().strip().split()
arr = []
for i in second:
    arr.append(int(i))

def bubbleSort(arr):
    for i in range(len(arr)-1):
        flag = False
        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                flag = True
        if flag == False:
            break
    for i in arr:
        task2_output.write(str(i)+" ")
bubbleSort(arr)

# Here if we don't keep a flag then in best case both loops will run fully making it o(n^2). By keeping a flag it only runs 1 time in best case making it O(n)