# -*- coding: utf-8 -*-
"""task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDq-XTyJ-Chu-ZpCimAl4lCTG2_7IgVw
"""

#Task 1b:

task1b_input = open(input1b.txt', mode='r')
task1b_output = open(output1b.txt', mode='w')

num_of_line = int(task1b_input.readline().strip())
for i in range(num_of_line):
    temp = task1b_input.readline().strip().split(" ")
    if temp[2] == "+":
        s = f"The result of {temp[1]} {temp[2]} {temp[3]} is {int(temp[1])+int(temp[3])}\n"
        task1b_output.write(s)
    elif temp[2] == "-":
        s = f"The result of {temp[1]} {temp[2]} {temp[3]} is {int(temp[1])-int(temp[3])}\n"
        task1b_output.write(s)
    elif temp[2] == "/":
        s = f"The result of {temp[1]} {temp[2]} {temp[3]} is {int(temp[1])/int(temp[3])}\n"
        task1b_output.write(s)
    else:
        s = f"The result of {temp[1]} {temp[2]} {temp[3]} is {int(temp[1])*int(temp[3])}\n"
        task1b_output.write(s)