# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YOX1foph-bIaD589yPv4grsutqV2wkeZ
"""

task2_input = open(file='input2.txt', mode='r')
task2_output = open(file='output2.txt', mode='w')

lst = task2_input.readline().strip().split(" ")
v = int(lst[0])
e = int(lst[1])

adj_list = {}
for i in range(1,v+1):
    adj_list[i] = []

for i in range(e):
    lst2 = task2_input.readline().strip().split()
    u = int(lst2[0])
    v = int(lst2[1])
    adj_list[u].append(v)
    adj_list[v].append(u)

queue = []

def bfs(grph,st):
    visited = [False]*(v+1)
    visited[0] = True
    queue.append(st)
    while queue:
        x = queue.pop(0)
        task2_output.write(str(x)+ " ")
        visited[x] = True
        for i in adj_list[x]:
            if visited[i] == False:
                visited[i] = True
                queue.append(i)

ans = bfs(adj_list,1)