# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YOX1foph-bIaD589yPv4grsutqV2wkeZ
"""

task4_input = open(file='input4.txt', mode='r')
task4_output = open(file='output4.txt', mode='w')

lst = task4_input.readline().strip().split(" ")
v = int(lst[0])
e = int(lst[1])
num = 0

adj_list = {}
for i in range(1,v+1):
    adj_list[i] = []

for i in range(e):
    lst2 = task4_input.readline().strip().split()
    x = int(lst2[0])
    y = int(lst2[1])
    adj_list[x].append(y)

for k,v in adj_list.items() :
  visited = [k]
  queue = [k]

  while queue :
    t = queue.pop(0)

    for x in adj_list[t] :

      if x == k:
        num += 1
      if x not in visited:
        visited.append(x)
        queue.append(x)

if num == 0:
    task4_output.write("No")
else:
    task4_output.write("Yes")