# -*- coding: utf-8 -*-
"""Task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YOX1foph-bIaD589yPv4grsutqV2wkeZ
"""

f1 = open("input6.txt", "r")
f2 = open("output6.txt", "w")

rows, columns = map(int, f1.readline().split())

graph = []
for r in range(rows):
    line = f1.readline().strip()
    row1= []
    for ch in line:
        row1.append(ch)
    graph.append(row1)


count = 0
start = None

for i in range(rows):
    for j in range(columns):
        if graph[i][j] == '.' or graph[i][j] == 'D':
            visit = [[0 for _ in range(columns)] for _ in range(rows)]
            stack = [(i, j)]
            dim_count = 0

            while stack:
                x, y = stack.pop()
                if visit[x][y] == 0:
                    visit[x][y] = 1
                    if graph[x][y] == 'D':
                        dim_count += 1
                    
                    for dx, dy in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
                        nx, ny = x + dx, y + dy
                        if 0 <= nx < rows and 0 <= ny < columns and graph[nx][ny] != '#' and visit[nx][ny] == 0:
                            stack.append((nx, ny))

            if dim_count > count:
                count = dim_count
                start = (i, j)


f2.write(str(count))
print(count)


f1.close()
f2.close()