# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8hWPKm3tH_rrYw82iZM3rpkC6WCXk8Y
"""

task3_input = open(file='input3.txt', mode='r')
task3_output = open(file='output3.txt', mode='w')

lst = task3_input.readline().strip().split(" ")

v = int(lst[0])
e = int(lst[1])

visited = [False]*(v+1)
stack = []
adj_list = {}

for i in range(1,v+1):
    adj_list[i] = []

for i in range(e):
    lst2 = task3_input.readline().strip().split()
    u = int(lst2[0])
    v = int(lst2[1])
    adj_list[u].append(v)


def DFS (adj_list,st):
    visited[st] = True

    for i in adj_list[st]:

        if visited[i]==False:
            visited[i]=True
            DFS(adj_list, i)
    stack.append(st)

for i in adj_list:
    if not visited[i]:
        DFS(adj_list,i)

x = stack[::-1]
new_visit = [False]*(v+1)
new_adj = {}
for i in range(1,v+1):
    new_adj[i] = []

for i in adj_list:
    for j in adj_list[i]:
        new_adj[j].append(i)

def DFS__ (new_adj,k,ans):
    new_visit[k] = True

    for i in new_adj[k]:

        if new_visit[i]==False:
            new_visit[i]=True
            ans+=str(i)+ " "
            return DFS__(new_adj, i,ans)
        else:
            return ans

for k in x:
    if not new_visit[k]:
        final=str(k)+' '
        a=DFS__(new_adj, k,final)
        task3_output.write(a+"\n")

task3_input.close()
task3_output.close()