# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8hWPKm3tH_rrYw82iZM3rpkC6WCXk8Y
"""

task2_input = open(file='input2.txt', mode='r')
task2_output = open(file='output2.txt', mode='w')

lst = task2_input.readline().strip().split(" ")

v = int(lst[0])
e = int(lst[1])

adj_list = {}
parent = [0]*(v+1)

for i in range(1,v+1):
    adj_list[i] = []

for i in range(e):
    lst2 = task2_input.readline().strip().split()
    u = int(lst2[0])
    v = int(lst2[1])
    adj_list[u].append(v)


count = 0
queue = []
lis = ""

for i in adj_list:
    for j in adj_list[i]:
        parent[j] += 1

for i in range(1,v+1):
            if parent[i] == 0:
                queue.append(i)
                queue.sort()

while queue:
    x = queue.pop(0)
    lis += str(x) + " "


    for i in adj_list[x]:
        parent[i] -= 1
        if parent[i] == 0:
            queue.append(i)
            queue.sort()

    count += 1

if count != v:
    task2_output.write("IMPOSSIBLE")
else:
    task2_output.write(lis)

task2_input.close()
task2_output.close()