# -*- coding: utf-8 -*-
"""Task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8hWPKm3tH_rrYw82iZM3rpkC6WCXk8Y
"""

task1a_input = open(file='input1a.txt', mode='r')
task1a_output = open(file='output1a.txt', mode='w')

lst = task1a_input.readline().strip().split(" ")

v = int(lst[0])
e = int(lst[1])

visited = [False]*(v+1)
stack = []
adj_list = {}
for i in range(1,v+1):
    adj_list[i] = []

for i in range(e):
    lst2 = task1a_input.readline().strip().split()
    u = int(lst2[0])
    v = int(lst2[1])
    adj_list[u].append(v)


def DFS (adj_list,st):
    visited[st] = True

    for i in adj_list[st]:

        if visited[i]==False:
            visited[i]=True
            DFS(adj_list, i)
    stack.append(st)

for i in adj_list:
    if not visited[i]:
        DFS(adj_list,i)

if len(stack) != v:
    task1a_output.write("IMPOSSIBLE")

else:
    ans = ""
    x = stack[::-1]
    for i in x:
        ans += str(i) + " "

    task1a_output.write(ans)

task1a_input.close()
task1a_output.close()