# -*- coding: utf-8 -*-
"""Task2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5hfd4Um7SJaPlvgByZiUWGs0zFoHTyD
"""

#Task2a
task2a_input = open(file = 'input2a.txt', mode='r')
task2a_output = open(file = 'output2a.txt', mode='w')

first = int(task2a_input.readline().strip())
f_lis = task2a_input.readline().strip().split()
second = int(task2a_input.readline().strip())
s_lis = task2a_input.readline().strip().split()

n = []

for i in f_lis:
    n.append(int(i))
for j in s_lis:
    n.append(int(j))
n.sort()

for i in n:
    task2a_output.write(str(i) + " ")