# -*- coding: utf-8 -*-
"""Task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5hfd4Um7SJaPlvgByZiUWGs0zFoHTyD
"""

#Task1b
task1b_input = open(file = 'input1b.txt', mode='r')
task1b_output = open(file = 'output1b.txt', mode='w')

value = task1b_input.readline().strip().split(" ")
lis = task1b_input.readline().strip().split(" ")
x = int(value[0])
y = int(value[1])
i = 0
j = x -1
flag = True
while i<j:
    if int(lis[i]) + int(lis[j]) == y:
        s = f"{i+1} {j+1}"
        task1b_output.write(str(s))
        flag = False
        break

    elif int(lis[i]) + int(lis[j]) < y:
        j -=1
    elif int(lis[i]) + int(lis[j]) > y:
        i += 1
if flag == True:
    task1b_output.write("impossible")