# -*- coding: utf-8 -*-
"""Task2b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5hfd4Um7SJaPlvgByZiUWGs0zFoHTyD
"""

#Task2b
task2b_input = open(file = 'input2b.txt', mode='r')
task2b_output = open(file = 'output2b.txt', mode='w')
first = int(task2b_input.readline().strip())
f_lis = task2b_input.readline().strip().split()
second = int(task2b_input.readline().strip())
s_lis = task2b_input.readline().strip().split()

n = []
i = 0
j = 0

while i < len(f_lis) and j < len(s_lis):
    if f_lis[int(i)]<= s_lis[int(j)]:
        n.append(int(f_lis[i]))
        i += 1
    else:
        n.append(int(s_lis[j]))
        j += 1


while i < len(f_lis):
    n.append(int(f_lis[i]))
    i+=1

while j < len(s_lis):
    n.append(int(s_lis[j]))
    j+=1
for i in range(len(n)):
    task2b_output.write(str(n[i]) + " ")