# -*- coding: utf-8 -*-
"""Task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5hfd4Um7SJaPlvgByZiUWGs0zFoHTyD
"""

#Task 1a
task1a_input = open(file='input1a.txt', mode='r')
task1a_output = open(file='output1a.txt', mode='w')

value_line = task1a_input.readline()

x,y = value_line.strip().split(" ")
x = int(x)
y = int(y)
value_line1 = task1a_input.readline().strip().split(" ")
flag = True
for i in range(0,len(value_line1)-1):

    for j in range (i+1,len(value_line1)):

        if int(value_line1[i]) + int(value_line1[j]) == y:
            s = f"{i+1} {j+1}"
            task1a_output.write(str(s))
            flag = False
            break
if flag == True:
    task1a_output.write("impossible")