# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18VIT-kRKrafjoCOUimUq6ydJoLSJSm82
"""

#Task4

task4_input = open(file='input4.txt', mode='r')
task4_output = open(file='output4.txt', mode='w')

num = int(task4_input.readline().strip())
f_lis = task4_input.readline().strip().split()
arr = []
for i in f_lis:
    arr.append(int(i))

limit = int(task4_input.readline().strip())

list2 =[]
for i in range(limit):
    list2.append(int(task4_input.readline().strip()))


kth=''

def partition(arr, start, end):
    pivot = arr[end]
    i = start - 1
    for j in range(start, end):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[end] = arr[end],arr[i + 1]
    return i + 1


for i in list2:
    k = i
    start = 0
    end = len(arr) - 1

    while True:
        pivot_index = partition(arr, start, end)
        if pivot_index + 1  == k:
            kth+=f'{arr[pivot_index]}\n'
            break
        elif pivot_index + 1 < k :
            start = pivot_index + 1
        else:
            end = pivot_index - 1

task4_output.write(kth)