# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18VIT-kRKrafjoCOUimUq6ydJoLSJSm82
"""

#Task3

task3_input = open(file='input3.txt', mode='r')
task3_output = open(file='output3.txt', mode='w')

num = int(task3_input.readline().strip())
f_lis = task3_input.readline().strip().split()
arr = []
for i in f_lis:
    arr.append(int(i))


def quickSort(arr, st, end):
    if st < end:

        pivot_Idx = partition(arr, st, end)
        quickSort(arr, st, pivot_Idx-1)
        quickSort(arr, pivot_Idx+1, end)

    else:
        return arr

def partition(arr,st,end):
    pivot = arr[end]
    idx = st - 1

    for i in range(st,end):
        if arr[i]  <= pivot:
            idx += 1

            arr[idx], arr[i] = arr[i], arr[idx]

    arr[idx+1] , arr[end] = arr[end], arr[idx+1]

    return idx+1

quickSort(arr,0,len(arr)-1)

for i in range(len(arr)):
    task3_output.write(str(arr[i])+ " ")