# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19VFBjSX1xIt48tp7F3yWWtRg2qknqPee
"""

#task1

import heapq
import math
task1_input = open(file='input1_1.txt', mode='r')
task1_output = open(file='output1_1.txt', mode='w')


lst = task1_input.readline().strip().split(" ")

v = int(lst[0])
e = int(lst[1])

adj_list = {}

for i in range(1,v+1):
    adj_list[i] = []

for i in range(e):
    lst2 = task1_input.readline().strip().split()
    u = int(lst2[0])
    v = int(lst2[1])
    w = int(lst2[2])

    adj_list[u].append([v,w])

s = int(task1_input.readline().strip())


def Dijkstra(gr, src):
    p = {}
    dist = {}
    Q = []
    visited = []

    for itr in gr:
        p[itr] = None
        dist[itr] = math.inf
        Q.append([math.inf, itr])

    dist[src] = 0
    Q.append([0, src])

    while len(Q)!= 0:
        heapq.heapify(Q)
        check = heapq.heappop(Q)
        dis_u, u = check
        visited.append(u)


        for v in gr[u]:
            if v not in visited:
                alt = dis_u+v[1]
                if alt < dist[v[0]]:
                    dist[v[0]] = alt
                    p[v[0]] = u
                    heapq.heappush(Q,[alt, v[0]])
    return dist

x = Dijkstra(adj_list, s)

for i,j in x.items():
    if j is not math.inf:
        task1_output.write(str(j)+" ")
    else:
        task1_output.write(str(-1)+" ")

task1_input.close()
task1_output.close()