# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18VIT-kRKrafjoCOUimUq6ydJoLSJSm82
"""

#task3

task3_input = open(file='input3_1.txt', mode='r')
task3_output = open(file='output3_1.txt', mode='w')

num,pp = task3_input.readline().split(" ")

pp = int(pp)
num = int(num)

lis = [None]*(num+1)
for i in range(len(lis)):
    lis[i] = i
adj_list = {}

for i in range(1,num+1):
    adj_list[i] = [i]


for i in range(pp):
    lst2 = task3_input.readline().strip().split()
    x = int(lst2[0])
    y = int(lst2[1])
    par2 = lis[x]
    par = lis[y]
    for i in adj_list[par]:
        if i not in adj_list[par2]:
            adj_list[par2].append(i)
    lis[y] = par2
    task3_output.write(str(len(adj_list[par2]))+"\n")

task3_input.close()
task3_output.close()