# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18VIT-kRKrafjoCOUimUq6ydJoLSJSm82
"""

#task2

task2_input = open(file='input2_2.txt', mode='r')
task2_output = open(file='output2_2.txt', mode='w')

from queue import  PriorityQueue
q = PriorityQueue()
count = 0
num,pp = task2_input.readline().split(" ")

num = int(num)
pp = int(pp)

end_lis = [0]*(pp)

for i in range(num):
    x,y = task2_input.readline().split(" ")
    q.put((int(y),int(x)))

en , st = q.get()

count += 1
end_lis[0] = en

while q.empty()== False:
    en, st = q.get()
    end_lis.sort(reverse=True)
    for i in end_lis:
        if i <= st:
            count+= 1
            x = end_lis.index(i)
            end_lis[x] = en

        else:
            pass

task2_output.write(str(count))


task2_input.close()
task2_output.close()