# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18VIT-kRKrafjoCOUimUq6ydJoLSJSm82
"""

#task1
task1_input = open(file='input1_3.txt', mode='r')
task1_output = open(file='output1_3.txt', mode='w')

from queue import  PriorityQueue
q = PriorityQueue()

num = int(task1_input.readline())
ans_lis = []
count = 0
end = 0

for i in range(num):
    x,y = task1_input.readline().split(" ")
    q.put((int(y),int(x)))


while q.empty() == False:
    en, st = q.get()

    if end <= st :
        count += 1
        ans_lis.append([st,en])
        end = en

task1_output.write(str(count)+"\n")
for i in ans_lis:
    o = ""
    x,y = i[0],i[1]
    o += str(x)+ " " + str(y) + "\n"
    task1_output.write(o)

task1_input.close()
task1_output.close()